In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

data = {
    "study_hours": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    "attendance" : [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)

# 입력값과 정답 분리
X = df[["study_hours", "attendance"]]
y = df["pass_fail"]

model = DecisionTreeClassifier(random_state=42)
model.fit(X, y)

print("데이터 준비 완료")
print(f"학생 수: {len(df)}명") # 학생 수: %%명

데이터 준비 완료
학생 수: 10명

# 모델 정확도

- 학습에 사용한 데이터로 정확도 확인

In [2]:
accuracy = model.score(X, y)
print("모델 정확도:", accuracy) # 0~1 표시됨 -> 0~100%
print(f"모델 정확도 퍼센트:{accuracy * 100}%")

모델 정확도: 1.0
모델 정확도 퍼센트:100.0%

In [3]:
# 모델이 어떤 예측을 했는지 확인
predictions = model.predict(X)

# Columns - 공부시간, 출석률, 실제, 예측, 결과
# zip() => zip([1,2,3], [4,5,6]) +> (1,4), (2,5), (3,6)
# 실제값과 예측값을 한쌍으로 묶어서...
result = pd.DataFrame({
    "공부시간": X["study_hours"].values,
    "출석률": X["attendance"].values,
    "실제": y.values,
    "예측": predictions,
    "결과": ["0" if a == p  else "X" for a, p in zip(y, predictions)]
})

result

   공부시간  출석률  실제  예측 결과
0     0   50   0   0  0
1     1   55   0   0  0
2     2   60   0   0  0
3     3   80   1   1  0
4     4   60   0   0  0
5     5   75   1   1  0
6     6   75   1   1  0
7     7   80   1   1  0
8     8   90   1   1  0
9     9   95   1   1  0

# 딕셔너리

Ket-Value 한쌍으로 이루어진 집합(자료형)

- List -> 번호표가 있는 사물함 (0번, 1번, 2번, ...)
- Dictionary -> 이름표가 있는 사물함 (학번, 이름, 학년)

In [4]:
# 리스트
student_list = ["kim", 20, 50]
print(f"리스트에서 이름 출력: {student_list[0]}")

# 딕셔너리
student_dict = {"name": "kim", "age": 20, "score": 50}
print(f"딕셔너리에서 이름 출력: {student_dict["name"]}")

리스트에서 이름 출력: kim
딕셔너리에서 이름 출력: kim

In [5]:
person = {
    "name": "아무개",
    "age": 20,
    "major" : "AI응용프로그래밍"
}

# 전체 출력
print(person)

# 나이
print(person["age"])

# 과목
print(person["major"])

{'name': '아무개', 'age': 20, 'major': 'AI응용프로그래밍'}
20
AI응용프로그래밍

In [6]:
person["age"] = 21
print(person["age"], person)

# 성별 추가
person["gender"] = "male"
print(person)

# 성별 삭제
del person["gender"]
print(person)

21 {'name': '아무개', 'age': 21, 'major': 'AI응용프로그래밍'}
{'name': '아무개', 'age': 21, 'major': 'AI응용프로그래밍', 'gender': 'male'}
{'name': '아무개', 'age': 21, 'major': 'AI응용프로그래밍'}

 
# 문제
- 사과, 바나나, 포도는 각 1000원, 2000원, 3000원 이다.  
    - 딕셔너리 로그 출력
- 사과의 가격을 10% 할인하고 바나나는 13% 인상했을 때,  
    - Python 코드로 작성
- 사과, 바나나, 포도의 가격표를 표시하세요.
    - 로그 출력 (DataFrame 사용)

## 딕셔너리와 반복문 함께 사용

In [7]:
scores = {
    "국어": 88,
    "수학": 76,
    "영어": 92
}

# 로그 출력 -------
# 국어: 88점
# 수학: 76점
# 영어: 92점

for subject, score in scores.items():
    print(f"{subject}: {score}점")

국어: 88점
수학: 76점
영어: 92점

In [8]:
# 80점 이상인 과목만 출력

for subject, score in scores.items():
    if score >= 80:
        print(f"80점 이상인 과목: {subject}")

80점 이상인 과목: 국어
80점 이상인 과목: 영어

# Pandas DataFrame 다루기

In [9]:
data = {
    "study_hours": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
    "attendance" : [50, 55, 60, 80, 60, 75, 75, 80, 90, 95],
    "pass_fail": [0, 0, 0, 1, 0, 1, 1, 1, 1, 1]
}

df = pd.DataFrame(data)
df

   study_hours  attendance  pass_fail
0            0          50          0
1            1          55          0
2            2          60          0
3            3          80          1
4            4          60          0
5            5          75          1
6            6          75          1
7            7          80          1
8            8          90          1
9            9          95          1

In [10]:
# 상위 3줄만 보기

df.head(3)

   study_hours  attendance  pass_fail
0            0          50          0
1            1          55          0
2            2          60          0

In [ ]:
# 기본 통계 보기
# count - 데이터 개수
# mean - 평균값 (전체 나누기 개수)
# std - 표준편차 (평균에서 얼마나 퍼져있는지, 클수록 편차가 큼)
# min - 최솟값
# 25% - 하위 25%
# 50% - 중앙값
# 75% - 상위 25%
# max - 최대값

df.describe()

       study_hours  attendance  pass_fail
count     10.00000   10.000000  10.000000
mean       4.50000   72.000000   0.600000
std        3.02765   15.129074   0.516398
min        0.00000   50.000000   0.000000
25%        2.25000   60.000000   0.000000
50%        4.50000   75.000000   1.000000
75%        6.75000   80.000000   1.000000
max        9.00000   95.000000   1.000000